# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-10 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=500, verbose_name='\u6587\u7ae0\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='users.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
